spring.application.name=help-desk-backend

#Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/spring_ai
spring.datasource.username=root
spring.datasource.password=root

# Hibernate/JPA Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Overriding the default Ollama port or host
spring.ai.ollama.base-url=http://localhost:11434

# Specify the model you have downloaded locally
spring.ai.ollama.chat.options.model=llama3.2:latest
