spring.application.name=help-desk-backend

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Gemini
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-3.8-flash
spring.ai.google.genai.chat.options.temperature=0.5

# Chat Memory
spring.ai.chat.memory.repository.jdbc.initialize-schema=always
