spring.application.name=help-desk-backend

#Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/helpdesk
spring.datasource.username=root
spring.datasource.password=root

# Hibernate/JPA Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.ai.google.genai.api-key=AQ.Ab8RN6IqJZrUw_2YZ8cNkZKzl4pOtaPRThg6XCE1lSPvAbw7Kw
spring.ai.google.genai.chat.options.model=gemini-3.8-flash
spring.ai.google.genai.chat.options.temperature=0.5

spring.ai.chat.memory.repository.jdbc.initialize-schema=always
